### ISSUE TITLE
callables only work on php 7

### ISSUE THREAD

**Issue by zkiiito** [LExpress/sfDoctrineGuardPlugin#5]
the readme says I have to specify callables this way:
```
all:
  sf_guard_plugin:
    algorithm_callable: [MyCryptoClass, MyCryptoMethod]
```

and in the code you've changed call_user_func_array to direct call:
https://github.com/LExpress/sfDoctrineGuardPlugin/commit/ca8003f8735671a83afb943820c2deb4b85f95b1#diff-34a6edffcedfeb5921fd37cb94d81bc3L106

(at line 79 too)

this only works on php7, if the callable is an array:
https://3v4l.org/CFtmD

**Comment by j0k3r** [comment]
Reading the code change, this means we no longer support `call_user_func_array`. And I honestly have no idea why.. 😕

**Comment by zkiiito** [comment]
this way it's not BC at all. should I file a pull request?
